[tool.poetry]
name = "disc"
version = "0.1.0"
description = ""
authors = ["DHH24 Hackathon <dhh-hackathon@helsinki.fi>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = "^2.2.2"
seaborn = "^0.12.2"
PyMySQL = "^1.1.1"
hereutil = "^0.1.3"
keyring = "^25.2.0"
jupytext = "^1.16.1"
jupyterlab = "^4.1.8"
SQLAlchemy = "^2.0.29"
click = "^8.1.7"
pyzstd = "^0.15.10"
mariadb = "^1.1.10"
tqdm = "^4.66.2"
findspark = "^2.0.1"
pyspark = "^3.5.1"
s3fs = "^2024.3.1"
pyarrow = "^16.0.0"
stanza = "^1.8.2"
ipywidgets = "^8.1.2"
dagster = "^1.7.4"
dagster-webserver = "^1.7.4"
dagster-mysql = "^0.23.4"
dagster-shell = "^0.23.4"
scipy = "^1.13.0"
transformers = "^4.40.2"
peft = "^0.10.0"

[tool.poetry.dev-dependencies]

[tool.dagster]
module_name = "dagster_assets"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
