---
title: "Civility annotation set"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    code_folding: hide
    toc: yes
  md_document:
    variant: gfm 
    toc: yes
---

```{r setup}
source(here::here("src/common_basis.R"))
```

```{r}
d1 <- cmw_stop_arguing_comment_ancestors_a %>%
  select(id=ancestor_id) %>%
  inner_join(cmw_comments_a) %>%
  distinct(link_id) %>%
  slice_sample(n=5) %>%
  inner_join(cmw_comments_a) %>%
  inner_join(cmw_stop_arguing_comment_ancestors_a, join_by(id==ancestor_id)) %>%
  select(-height,-id.y) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
d2 <- cmw_stop_arguing_comment_descendants_a %>%
  select(id=descendant_id) %>%
  inner_join(cmw_comments_a) %>%
  distinct(link_id) %>%
  slice_sample(n=5) %>%
  inner_join(cmw_comments_a) %>%
  inner_join(cmw_stop_arguing_comment_descendants_a, join_by(id==descendant_id)) %>%
  select(-height,-id.y) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
d3 <- cmw_comments_a %>% 
  distinct(link_id) %>%
  slice_sample(n=5) %>%
  inner_join(cmw_comments_a) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
d4 <- data_driven_civil_discourse_subset_a %>% 
  distinct(link_id) %>%
  slice_sample(n=20) %>%
  inner_join(data_driven_civil_discourse_subset_a) %>%
  select(-height) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
d5 <- aita_comments_a %>% 
  distinct(link_id) %>%
  slice_sample(n=5) %>%
  inner_join(aita_comments_a) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
d6 <- eli5_comments_a %>% 
  distinct(link_id) %>%
  slice_sample(n=5) %>%
  inner_join(eli5_comments_a) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
d7 <- unpopularopinion_comments_a %>% 
  distinct(link_id) %>%
  slice_sample(n=5) %>%
  inner_join(unpopularopinion_comments_a) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
d8 <- best_of_reddit_comments_a %>% 
  distinct(link_id) %>%
  slice_sample(n=10) %>%
  inner_join(best_of_reddit_comments_a) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
d9 <- random_sample_comments_a %>% 
  distinct(link_id) %>%
  slice_sample(n=20) %>%
  inner_join(random_sample_comments_a) %>%
  group_by(link_id) %>%
  slice_sample(n=1) %>%
  ungroup() %>%
  compute_a()
```

```{r}
annotation_set <- d1 %>% 
  union_all(d2) %>%
  union_all(d3) %>%
  union_all(d4) %>%
  union_all(d5) %>%
  union_all(d6) %>%
  union_all(d7) %>%
  union_all(d8) %>%
  union_all(d9) %>%
  distinct() %>%
  compute_a()
```

```{r}
op_texts <- annotation_set %>% 
  inner_join(cmw_submissions_a, join_by(link_id==id)) %>%
  union_all(annotation_set %>% 
    inner_join(aita_submissions_a, join_by(link_id==id))) %>%
  union_all(annotation_set %>% 
    inner_join(eli5_submissions_a, join_by(link_id==id))) %>%
  union_all(annotation_set %>% 
    inner_join(unpopularopinion_submissions_a, join_by(link_id==id))) %>%
  union_all(annotation_set %>% 
    inner_join(best_of_reddit_submissions_a, join_by(link_id==id))) %>%
  union_all(annotation_set %>% 
    inner_join(random_sample_submissions_a, join_by(link_id==id))) %>%
  select(id,title,selftext,url) %>%
  compute_a()
```

```{r}
library(glue)
ancestors <- tbl(con, sql(glue("
WITH RECURSIVE comment_ancestors AS (
    SELECT id, parent_comment_id AS ancestor_id, 1 AS height 
    FROM {annotation_set %>% dbplyr::remote_name()}
    WHERE parent_comment_id IS NOT NULL
  UNION ALL
    SELECT ca.id, c.parent_comment_id AS ancestor_id, height + 1 AS height
    FROM comment_ancestors ca, cmw_comments_a c
    WHERE ca.ancestor_id = c.id AND c.parent_comment_id IS NOT NULL
)
SELECT id, ancestor_id FROM comment_ancestors"))) %>%
  compute_a()
```

```{r}
ancestor_texts <- ancestors %>%
  inner_join(cmw_comments_a, join_by(ancestor_id==id)) %>%
  union_all(ancestors %>% 
    inner_join(aita_comments_a, join_by(ancestor_id==id))) %>%
  union_all(ancestors %>% 
    inner_join(eli5_comments_a, join_by(ancestor_id==id))) %>%
  union_all(ancestors %>% 
    inner_join(unpopularopinion_comments_a, join_by(ancestor_id==id))) %>%
  union_all(ancestors %>% 
    inner_join(best_of_reddit_comments_a, join_by(ancestor_id==id))) %>%
  union_all(ancestors %>% 
    inner_join(random_sample_comments_a, join_by(ancestor_id==id))) %>%
  select(id,author,created_utc,body) %>%
  group_by(id) %>%
  summarise(ancestor_text=sql("GROUP_CONCAT(CONCAT_WS('', author, ' @ ', created_utc, ' :\\n\\n', body) ORDER BY created_utc  SEPARATOR '\n--------------------------------\n\n')"))
```

```{r}
annotation_set %>%
  left_join(op_texts) %>%
  left_join(ancestor_texts) %>%
  mutate_all(as.character()) %>%
  collect() %>%
  write_tsv(here("data/work/civility_annotation_set.tsv"), quote="needed",na="")
```