---
title: "Civility annotation set"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    code_folding: hide
    toc: yes
  md_document:
    variant: gfm 
    toc: yes
---

```{r setup}
source(here::here("src/common_basis.R"))
library(irr)
```

```{r}
intervention_annotations <- read_csv(here("data/work/annotations/interventions-samuli-3.csv")) %>% 
  mutate(annotator="Samuli") %>%
  union_all(
    read_csv(here("data/work/annotations/interventions-ylva-3.csv")) %>% 
    mutate(annotator="Ylva") 
  ) %>% 
  bind_rows(
    read_csv(here("data/work/annotations/interventions-samuli-2.csv")) %>% 
    mutate(subreddit="cmw") %>%
    mutate(annotator="Samuli")
  ) %>% 
  bind_rows(
    read_csv(here("data/work/annotations/interventions-ylva-2.csv")) %>% 
    mutate(subreddit="cmw") %>%
    mutate(annotator="Ylva")
  )
```

```{r}
intervention_annotations %>% 
  filter(annotator=="Ylva") %>%
  select(permalink,intervention) %>% 
  inner_join(intervention_annotations %>% 
               filter(annotator=="Samuli") %>%
               select(permalink,intervention), join_by(permalink)) %>% 
 select(intervention.x,intervention.y) %>%
 as.matrix() %>% 
 kappa2()
```


```{r}
intervention_annotations %>% 
  filter(annotator=="Ylva") %>%
  select(permalink,intervention,body) %>% 
  inner_join(intervention_annotations %>% 
               filter(annotator=="Samuli") %>%
               select(permalink,intervention), join_by(permalink)) %>% 
  count(intervention.x,intervention.y) %>% 
  ggplot(aes(x=intervention.x,y=intervention.y,fill=n,label=n)) + 
  geom_tile() + 
  xlab("Ylva") +
  ylab("Samuli") +
  theme_hsci_continuous() + 
  geom_label(fill="white")
```

```{r}
intervention_annotations %>% 
  filter(annotator=="Ylva") %>%
  select(permalink,intervention_ylva=intervention,body) %>% 
  inner_join(intervention_annotations %>% 
               filter(annotator=="Samuli") %>%
               select(permalink,intervention_samuli=intervention), join_by(permalink)) %>%
  filter(intervention_ylva!=intervention_samuli)
```

```{r}
intervention_annotations_long <- intervention_annotations %>%
  pivot_longer(c(ap,dd,fm,im,is,jc,mc,md,pd),names_to="measure") %>%
  mutate(value=as.integer(str_extract(value, "\\[\\{\"rating\":(\\d)\\}\\]", group=1)))

```

```{r}
intervention_annotations_long %>% 
  filter(intervention %in% c("Yes","No")) %>%
  group_by(intervention,measure) %>% 
  summarise(mvalue=mean(value,na.rm=T)) %>% 
  ggplot(aes(x=measure,y=mvalue,color=intervention)) + 
  geom_point() +
  coord_flip() +
  theme_hsci_discrete()
```

```{r}
intervention_annotations %>%
  group_by(subreddit,permalink) %>%
  summarise(intervention=all(intervention=="Yes",na.rm=T)) %>%
  count(subreddit,intervention) %>%
  group_by(subreddit) %>%
  mutate(prop=n/sum(n))
```

