---
title: "Eetu's scratch"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    code_folding: hide
    toc: yes
  md_document:
    variant: gfm 
    toc: yes
---

```{r setup}
source(here::here("src/common_basis.R"))
```

# Counts of submissions and comments through time

```{r}
ls(pattern=("[^_]*_submissions_[a]")) %>% 
  map(\(x)
      get(x) %>% 
        mutate(year=year(created_utc)) %>% 
        count(year) %>% 
        collect() %>% 
        mutate(dataset=x)) %>% 
  reduce(union_all) %>%
  ggplot(aes(x=year,y=n, color=dataset)) +
  geom_line() +
  geom_point() +
  theme_hsci_discrete() +
  scale_y_continuous(labels=scales::number, breaks=seq(0,1000000, by=50000)) +
  scale_x_continuous(breaks=seq(2005,2024,by=2)) +
  ggtitle("Submissions by year")
```


```{r}
ls(pattern=("[^_]*_comments_[a]")) %>% 
  map(\(x)
      get(x) %>% 
        mutate(year=year(created_utc)) %>% 
        count(year) %>% 
        collect() %>% 
        mutate(dataset=x)) %>% 
  reduce(union_all) %>%
  ggplot(aes(x=year,y=n, color=dataset)) +
  geom_line() +
  geom_point() +
  theme_hsci_discrete() +
  scale_y_continuous(labels=scales::number, breaks=seq(0,50000000, by=2000000)) +
  scale_x_continuous(breaks=2010:2023) +
  ggtitle("Comments by year")
```

# Comments per submissions distribution through time

```{r}
cmw_submissions_a %>%
  transmute(year=year(created_utc), num_comments) %>%
  filter(year<2024L) %>%
  ggplot(aes(x=year,group=year,y=num_comments)) +
  #geom_quasirandom() +
  geom_boxplot() +
  theme_hsci_discrete() +
  scale_y_continuous(labels=scales::number) +
  scale_x_continuous(breaks=2013:2023) +
  coord_cartesian(ylim=c(0,200)) +
  xlab("Year") +
  ylab("Comments per submission")
```

# Delta comment analyses

```{r}
cmw_delta_comments_a %>% 
  select(id=link_id) %>%
  count(id) %>% 
  right_join(
    cmw_submissions_a %>%
      mutate(year=year(created_utc)) %>%
      filter(year<2024L)
    , join_by(id)
  ) %>%
  replace_na(list(n=0)) %>%
  mutate(n=pmin(n,5)) %>%
  count(year,n, name="nn") %>%
  group_by(year) %>%
  mutate(prop=nn/sum(nn)) %>%
  ungroup() %>%
  filter(n>0) %>%
  collect() %>%
  mutate(n=if_else(n>=5,">=5",as.character(n)) %>% fct_relevel(">=5",after=Inf)) %>%
  ggplot(aes(x=year,y=prop,fill=n)) +
  geom_col() +
  theme_hsci_discrete() +
  theme(legend.position="bottom") +
  scale_y_continuous(labels=scales::percent) +
  scale_x_continuous(breaks=2013:2023) +
  labs(fill="N deltas awarded") +
  xlab("Year") +
  ylab("Proportion of submissions") +
  ggtitle("Number of deltas awarded per submission through the years")

```



```{r}
delta_comment_depth <- tbl(con, sql("
WITH RECURSIVE delta_comment_ancestors AS (
    SELECT id, parent_comment_id AS ancestor_id, 0 AS height 
    FROM cmw_delta_comments_a
  UNION ALL
    SELECT ca.id, c.parent_comment_id AS ancestor_id, height + 1 AS height
    FROM delta_comment_ancestors ca, cmw_comments_a c
    WHERE ca.ancestor_id = c.id
),
delta_comment_depth AS (
  SELECT id, MAX(height) AS depth
  FROM delta_comment_ancestors
  GROUP BY id
)
SELECT * FROM delta_comment_depth
")) %>% compute_a()
```


```{r}
delta_comment_depth %>%
  count(depth) %>%
  ggplot(aes(x=depth,y=n)) +
  geom_col() +
  theme_hsci_discrete() +
  scale_y_continuous(labels=scales::number) +
  scale_x_continuous(breaks=1:190) +
  coord_cartesian(xlim=c(0,15)) +
  xlab("Depth of delta'd comment") +
  ylab("N")
```


```{r}
cmw_submissions_a %>% 
  left_join(cmw_delta_comments_a %>% select(id=link_id) %>% count(id, name="deltas")) %>%
  replace_na(list(deltas=0)) %>%
  count(deltas) %>%
  ggplot(aes(x=deltas,y=n)) +
  geom_col() +
  theme_hsci_discrete() +
  scale_y_continuous(labels=scales::number) +
  scale_x_continuous(breaks=0:190) +
  coord_cartesian(xlim=c(0,15)) +
  xlab("Number of deltas per submission") +
  ylab("N submissions")
```

```{r}
library(ggpointdensity)
cmw_submissions_a %>% 
  left_join(cmw_delta_comments_a %>% select(id=link_id) %>% count(id, name="deltas")) %>%
  replace_na(list(deltas=0)) %>%
  mutate(has_deltas=deltas>0) %>%
  count(num_comments, has_deltas) %>%
  group_by(num_comments) %>%
  filter(n>=150) %>%
  mutate(prop=n/sum(n)) %>%
  ungroup() %>%
  filter(has_deltas) %>%
  ggplot(aes(x=num_comments,y=prop,weight=n)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks=seq(0,8000,by=10)) +
  theme_hsci_continuous() +
  scale_y_continuous(labels=scales::percent) +
  xlab("Number of comments under submission") +
  ylab("Proportion of submissions having a delta")
```

```{r}
cmw_delta_comments_a %>% 
  group_by(link_id) %>% 
  summarise(earliest_delta=min(created_utc),.groups="drop") %>%
  inner_join(cmw_comments_a, join_by(link_id)) %>%
  mutate(before=created_utc<earliest_delta) %>%
  count(link_id, before) %>%
  ggplot(aes(x=before,y=n)) +
  geom_boxplot() +
  theme_hsci_discrete()
```


